# NumPy Tutorial 

In [1]:
import numpy as np

In [2]:
myarr = np.array([(12,32,45,65,21),(1,5,2,4,5)], np.int32)

In [3]:
myarr[0,1]

32

In [4]:
myarr.shape

(2, 5)

In [5]:
myarr.dtype

dtype('int32')

# Array creation: conversion from other Python structures

In [6]:
listarray = np.array([[12,65,2],[1,5,2],[12,21,12]])

In [7]:
listarray


array([[12, 65,  2],
       [ 1,  5,  2],
       [12, 21, 12]])

In [8]:
zeros = np.zeros((2,5), np.int8)

In [9]:
zeros


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [10]:
rng = np.arange(12)

In [11]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
lspace = np.linspace(1,2,10)

In [13]:
lspace


array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [14]:
emp = np.empty((4,3))

In [15]:
emp

array([[1.28404641e-311, 2.81617418e-322, 0.00000000e+000],
       [0.00000000e+000, 1.11260619e-306, 2.46567317e+179],
       [4.22776054e-090, 1.02290494e+166, 1.28340971e+160],
       [1.64759547e+185, 6.48224659e+170, 4.93432906e+257]])

In [16]:
emp_like = np.empty_like(lspace)

In [17]:
emp_like


array([1.28404641e-311, 2.81617418e-322, 1.11260619e-306, 2.46567317e+179,
       4.22776054e-090, 1.02290494e+166, 1.28340971e+160, 1.64759547e+185,
       6.48224659e+170, 4.93432906e+257])

In [18]:
ide = np.identity(10)

In [19]:
ide


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
ide.shape

(10, 10)

In [21]:
ar = np.arange(20)

In [22]:
ar


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
ar = ar.reshape((4,5))

In [24]:
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [25]:
ar.shape

(4, 5)

In [26]:
ar = ar.ravel()


In [27]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
ar.shape

(20,)

# Numpy Axis

In [29]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [30]:
x


[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [31]:
ar = np.array(x)

In [32]:
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [33]:
ar.sum(axis = 0)

array([12,  8,  9])

In [34]:
ar.sum(axis = 1)

array([ 6, 15,  8])

# Transpose

In [35]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [36]:
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [37]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [38]:
ar.flat

In [39]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [40]:
ar.ndim

2

In [41]:
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [42]:
ar.size

9

In [43]:
ar.nbytes

36

In [44]:
one = np.array([11,983,54])

In [45]:
one

array([ 11, 983,  54])

In [46]:
one.argmax()

1

In [47]:
one.argmin()

0

In [48]:
one.argsort()

array([0, 2, 1], dtype=int64)

In [49]:
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [50]:
ar.argmax(axis = 0)

array([2, 1, 1], dtype=int64)

In [51]:
ar.argmax(axis = 1)

array([2, 2, 0], dtype=int64)

In [52]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [53]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [54]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [55]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [56]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

# Proof of taking lesser space


In [57]:
import sys

In [58]:
py_ar = [1,2,3,4,5]

In [59]:
np_ar = np.array(py_ar)

In [60]:
sys.getsizeof(py_ar)

104

In [61]:
sys.getsizeof(np_ar)

116

In [62]:
np_ar.size

5